DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS chat CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS users_chat CASCADE;
DROP TABLE IF EXISTS company_locales CASCADE;
DROP TABLE IF EXISTS company CASCADE;
